{% set name = "gpcam" %}
{% set version = "8.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/gpCAM/archive/{{ version }}.tar.gz
  sha256: 0959e1d30e36e802ee9022113f35449e635ee11bd3e31e5846111f747fd7e30f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy <2.2.7,>=2.2.6
    - scipy >=1.16.0,<1.17
    - dask-core >=2025.5.1
    - distributed >=2025.5.1
    - fvgp =4.7.5
    - loguru

test:
  imports:
    - gpcam
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gpcam.lbl.gov
  summary: gpCAM is a code for autonomous data acquisition
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
