{% set name = "gpcam" %}
{% set version = "7.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/gpCAM/archive/{{ version }}.tar.gz
  sha256: 9f70c361bd3e56f98de2e8f994a9be64fdebf32941e40c54545a703774ac6718
  patches:
    - zmq.patch
    - dep.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy ==1.9.1
    - matplotlib-base
    - pytorch >=1.9.0
    - pandas
    - ophyd
    - dask-core >=2021.6.2
    - distributed >=2021.6.2
    - pyzmq
    - fvgp ==3.3.7
    - plotly
    - notebook
    - loguru

test:
  imports:
    - gpcam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gpcam.lbl.gov
  summary: gpCAM is a code for autonomous data acquisition
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
