{% set name = "gpcam" %}
{% set version = "8.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/gpCAM/archive/{{ version }}.tar.gz
  sha256: a0816ac88b8a5fa502c3708b541e40a1e80210823b07b3ef38b7fd073574775b
  patches:
    - zmq.patch
    - dep.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy ==1.9.1
    - matplotlib-base
    - pytorch >=1.9.0
    - pandas
    - ophyd
    - dask-core >=2021.6.2
    - distributed >=2021.6.2
    - pyzmq
    - fvgp ==3.3.8
    - plotly
    - notebook
    - loguru

test:
  imports:
    - gpcam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gpcam.lbl.gov
  summary: gpCAM is a code for autonomous data acquisition
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
