{% set name = "gpcam" %}
{% set version = "8.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lbl-camera/gpCAM/archive/{{ version }}.tar.gz
  sha256: 053ba45f7f0b6a7f1c42d88712d10b018ef0853bdbaf4f1bad18ec2d906cff8c
  patches:
    - zmq.patch
    - dep.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy <1.25.0,>=1.18.5
    - scipy ==1.9.1
    - matplotlib-base
    - pytorch >=1.9.0
    - pandas
    - ophyd
    - dask-core >=2021.6.2
    - distributed >=2021.6.2
    - pyzmq
    - fvgp ==3.3.8
    - plotly
    - notebook
    - loguru

test:
  imports:
    - gpcam
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gpcam.lbl.gov
  summary: gpCAM is a code for autonomous data acquisition
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
